- name: Enable UFW
  ansible.builtin.command: ufw --force enable
  become: true

- name: Allow Nginx
  ansible.builtin.command: ufw allow "Nginx Full"
  become: true

- name: Allow PostgreSQL
  ansible.builtin.command: ufw allow 5432/tcp
  become: true
